# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://tiernanotoolephotography.com
title: Tiernan OToole Photography
email: tiernan@tiernanotoole.ie
author: Tiernan OToole
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/tiernano
  - title: github
    url: https://github.com/tiernano
  - title: linkedin
    url: https://ie.linkedin.com/in/tiernano
